spring:
  application:
    name: Journal App

  data:
    mongodb:
      uri:
      database: journalDB
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587 
    username: 
    password:
    properties:
      mail: 
        smtp:
          auth: true 
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /app
