spring:
  application:
    name: Journal App

  data:
    mongodb:
      uri: mongodb+srv://farhanakhtar7869:Farhan123@cluster22.tt7imeu.mongodb.net/
      database: journalDB
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /app
